Text bug fixes
diffgram/diffgram pull request #1208
Opened 2022-11-22 15:54 UTC by vitalii-bulyzhyn

## Description
...

### Author Checklist
_All items are required. Please add a note to the item if the item is not applicable and please add links to any relevant follow up issues._

I have...

* [ ]  added `!` to the type prefix if Breaking Changes.
* [ ]  considered the impact to the SDK.
* [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ]  provided a link to the relevant issue in JIRA or Github Link in PR.
* [ ]  included the unit and integration tests
* [ ]  included comments & docs for new API Endpoints
* [ ]  updated the relevant documentation or specification in readme.io
* [ ]  reviewed "Files changed" and left comments if necessary
* [ ]  confirmed all CI checks have passed

Breaking Changes including adding required params.

### Reviewers Checklist
_All items are required. Please add a note if the item is not applicable and please add your handle next to the items reviewed if you only reviewed selected items._

I have...

* [ ]  confirmed the Author checklist was followed
* [ ]  reviewed API design and naming
* [ ]  reviewed documentation is accurate
* [ ]  reviewed tests and test coverage
* [ ]  manually tested (if applicable)

2022-11-23 20:29 UTC, vitalii-bulyzhyn commented
Way to reproduce freezing bug:

<img width="1512" alt="Screenshot 2022-11-23 at 17 28 48" src="https://user-images.githubusercontent.com/46309116/203640501-08579a53-643f-469f-b56c-323c4846e349.png">

2022-11-25 17:52 UTC, anthony-sarkis commented on frontend/src/components/text_annotation/text_annotation_core.vue
> +      <div v-if="rendering">Loading...</div>
@vitalii-bulyzhyn  want to add v-linear loader here? like from image case?

2022-11-28 14:15 UTC, PJEstrada requested changes
Hey Vitalii! this is the only  thing I got:

1. When displaying the labels menu sometimes it gets hidden by the toolbar
![image](https://user-images.githubusercontent.com/6606958/204297946-2a860b8c-c057-4916-aa32-eb2f6466c41a.png)
I think the fix might be to add a scrollbar to the labels menu 

For the rest of issues I think they are all fixed now Vitalii thanks a lot :)

2022-11-29 17:42 UTC, anthony-sarkis commented
Great work Vitalii, I tested most of these again on QA and all worked as expected.

2022-11-29 17:43 UTC, anthony-sarkis approved these changes

2022-11-30 15:36 UTC, PJEstrada approved these changes
Thanks Vitalii!

2022-11-30 18:00 UTC, merged